server:
  port: 8080

spring:
  application:
    name: ecommerce-backend
  
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${EMAIL_USERNAME:your-email@gmail.com}
    password: ${EMAIL_PASSWORD:your-app-password}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

# Configurações do Supabase
supabase:
  url: ${SUPABASE_URL:https://your-project.supabase.co}
  anon-key: ${SUPABASE_ANON_KEY:your-anon-key}
  service-role-key: ${SUPABASE_SERVICE_ROLE_KEY:your-service-role-key}

logging:
  level:
    com.ecommerce.backend: DEBUG
    org.springframework.web: DEBUG
